apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  installation_tag: "Kiali - bsd Custom"
  auth:
    strategy: anonymous

  external_services:

    custom_dashboards:
      discovery_auto_threshold: 10
      discovery_enabled: "auto"
      enabled: true
      is_core: false
      # namespace_label: "namespace"
      prometheus:
        auth:
          ca_file: ""
          insecure_skip_verify: false
          password: ""
          token: ""
          type: "none"
          use_kiali_token: false
          username: ""
        cache_duration: 10
        cache_enabled: true
        cache_expiration: 300
        # # default: custom_headers is empty
        # custom_headers:
        #   customHeader1: "customHeader1Value"
        # health_check_url: ""
        # is_core: true
        # # default: query_scope is empty
        # query_scope:
        #   mesh_id: "mesh-1"
        #   cluster: "cluster-east"
        thanos_proxy:
          enabled: false
          retention_period: "12h"
          scrape_interval: "30s"
        url: "http://kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"

    grafana:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: "test123"
        token: ""
        type: "basic"
        use_kiali_token: false
        username: "admin"
      dashboards:
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          service: "var-service"
      - name: "Istio Workload Dashboard"
        variables:
          namespace: "var-namespace"
          workload: "var-workload"
      - name: "Istio Mesh Dashboard"
      - name: "Istio Control Plane Dashboard"
      - name: "Istio Performance Dashboard"
      - name: "Istio Wasm Extension Dashboard"
      enabled: true
      health_check_url: ""
      # default: in_cluster_url is undefined
      in_cluster_url: "http://monitoring-grafana.monitoring"
      is_core: false
      url: "http://monitoring-grafana.monitoring.svc.cluster.local"

    istio:
      component_status:
        components:
        - app_label: "istiod"
          is_core: true
          is_proxy: false
        - app_label: "istio-ingressgateway"
          is_core: true
          is_proxy: true
          # default: namespace is undefined
          namespace: istio-system
        - app_label: "istio-egressgateway"
          is_core: false
          is_proxy: false
          # default: namespace is undefined
          namespace: istio-system
        enabled: true
      config_map_name: "istio"
      envoy_admin_local_port: 15000
      gateway_api_class_name: ""
      ## default: istio_canary_revision is undefined
      # istio_canary_revision:
      #   current: "1-9-9"
      #   upgrade: "1-10-2"
      istio_identity_domain: "svc.cluster.local"
      istio_injection_annotation: "sidecar.istio.io/inject"
      istio_sidecar_annotation: "sidecar.istio.io/status"
      istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
      istiod_deployment_name: "istiod"
      istiod_pod_monitoring_port: 15014
      root_namespace: "istio-system"
      url_service_version: ""

    prometheus:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      cache_duration: 10
      cache_enabled: true
      cache_expiration: 300
      ## default: custom_headers is empty
      # custom_headers:
      #   customHeader1: "customHeader1Value"
      health_check_url: ""
      is_core: true
      ## default: query_scope is empty
      # query_scope:
      #   mesh_id: "mesh-1"
      #   cluster: "cluster-east"
      thanos_proxy:
        enabled: false
        retention_period: "7d"
        scrape_interval: "30s"
      url: "http://kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"

    tracing:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      enabled: false
      in_cluster_url: "http://tracing.istio-system"
      is_core: false
      namespace_selector: true
      ## default: query_scope is empty
      # query_scope:
      #   mesh_id: "mesh-1"
      #   cluster: "cluster-east"
      url: "https://jaeger.51bsd.click/"
      use_grpc: true
      whitelist_istio_system: ["jaeger", "istio-ingressgateway"]

  deployment:
    ingress:
      enabled: true
      class_name: alb
      override_yaml:
        metadata:
          annotations:
            alb.ingress.kubernetes.io/scheme: "internet-facing"
            alb.ingress.kubernetes.io/target-type: "ip"
            alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\": 443}]"
            alb.ingress.kubernetes.io/backend-protocol: "HTTP"
            alb.ingress.kubernetes.io/ssl-redirect: "443"
            alb.ingress.kubernetes.io/group.name: "monitoring-alb-group"
        spec:
          rules:
          - host: kiali.51bsd.click
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: kiali
                    port:
                      number: 20001
    # "**" <- all namespaces 
    accessible_namespaces: ["**"]
      # - "bookinfo"
      # - "ops_.*"
    view_only_mode: false
  server:
    web_root: "/"
  